### ISSUE TITLE
首次验证失败，但应该是验证成功了，因为第二次不用验证

### ISSUE THREAD

**Issue by lin-junliang** [win-syswow64/GT-Manual-Plugin#1]
![image](https://github.com/user-attachments/assets/f0ee61df-c0bc-43d3-82f3-f931aa9c347c)

第一次验证完总是会提示出现验证码，但实际上应该是验证成功了，因为立刻试第二次就不用验证了，有没有办法让第一次就验证成功？

**Comment by win-syswow64** [comment]
更新一下崽和插件试试，有点抽象

**Comment by win-syswow64** [comment]
现在这个版本我没有遇到过这个问题了

**Comment by win-syswow64** [comment]
此issue将因超时未回复而关闭。
