### ISSUE TITLE
更新 url 之后，跳转的 url 没有进行相应的修改

### ISSUE THREAD

**Issue by ZM-J** [win-syswow64/GT-Manual-Plugin#2]
`config.yaml` 已经更新完 `gt-manual.xingdream.top/mysSign` 之后，跳转的页面仍然是 `https://GT-Manual.ganyu.us.kg/mysSign/xxx`，而没有更新为新的域名

**Comment by win-syswow64** [comment]
已修复，本次修复无需更新。
